// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA67DdxWdF8BvwAq_3ekkl80hRTHl2DhQ',
    appId: '1:554097756035:web:8cd6558b968a89daf6d8b6',
    messagingSenderId: '554097756035',
    projectId: 'gramgrid-4d683',
    authDomain: 'gramgrid-4d683.firebaseapp.com',
    storageBucket: 'gramgrid-4d683.appspot.com',
    measurementId: 'G-8DWMX3FJWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIAfPrGM05BTG0cJwep2xMeCS9QHDLr6w',
    appId: '1:554097756035:android:5f74143ed70cd14bf6d8b6',
    messagingSenderId: '554097756035',
    projectId: 'gramgrid-4d683',
    storageBucket: 'gramgrid-4d683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQHsgPadxfzuCW0Du752RxlhtVEvJSQFM',
    appId: '1:554097756035:ios:eb5eca335c6298c6f6d8b6',
    messagingSenderId: '554097756035',
    projectId: 'gramgrid-4d683',
    storageBucket: 'gramgrid-4d683.appspot.com',
    iosBundleId: 'com.oorischubert.gridgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQHsgPadxfzuCW0Du752RxlhtVEvJSQFM',
    appId: '1:554097756035:ios:e334f275e275b21af6d8b6',
    messagingSenderId: '554097756035',
    projectId: 'gramgrid-4d683',
    storageBucket: 'gramgrid-4d683.appspot.com',
    iosBundleId: 'com.example.gridgram',
  );
}
